FROM python:3.8 as requirements-stage

# install poetry
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
ENV PATH="${PATH}:/root/.poetry/bin"
 
# create dir and install packages
WORKDIR /app
ENV PYTHONPATH="/app"
COPY pyproject.toml .
RUN poetry install

COPY . .
# CHANGE CONFIG FILE
COPY ./app/core/config.dev.py ./app/core/config.py
RUN chmod +x ./prestart.sh
RUN chmod +x ./run.sh

CMD ["bash", "-c", "poetry run ./prestart.sh ; poetry run ./run.sh"]