"""empty message

Revision ID: 88b5e8b19d14
Revises: 
Create Date: 2022-08-30 15:38:16.412915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b5e8b19d14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_user', sa.Boolean(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('app_type', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('submit_time', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submitter_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_id'), 'case', ['id'], unique=False)
    op.create_table('caseparams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('app', sa.String(length=256), nullable=False),
    sa.Column('accuracy_level', sa.String(length=256), nullable=False),
    sa.Column('pressure', sa.Float(), nullable=False),
    sa.Column('upper_temperature', sa.Float(), nullable=False),
    sa.Column('lower_temperature', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caseparams_id'), 'caseparams', ['id'], unique=False)
    op.create_table('caseparams_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('app', sa.String(length=256), nullable=False),
    sa.Column('accuracy_level', sa.String(length=256), nullable=False),
    sa.Column('country_selection', sa.String(length=256), nullable=False),
    sa.Column('load_selection', sa.String(length=256), nullable=True),
    sa.Column('load_value', sa.Float(), nullable=True),
    sa.Column('safety_factor', sa.Float(), nullable=False),
    sa.Column('has_profiles', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caseparams_2_id'), 'caseparams_2', ['id'], unique=False)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=False),
    sa.Column('htf', sa.String(length=256), nullable=False),
    sa.Column('material', sa.String(length=256), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('run_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_id'), 'result', ['id'], unique=False)
    op.create_table('result_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('tes_type', sa.String(length=256), nullable=False),
    sa.Column('tes_attr', sa.PickleType(), nullable=True),
    sa.Column('tes_op_attr', sa.PickleType(), nullable=True),
    sa.Column('chiller', sa.String(length=256), nullable=False),
    sa.Column('chiller_no_tes', sa.String(length=256), nullable=False),
    sa.Column('capex', sa.Float(), nullable=False),
    sa.Column('capex_no_tes', sa.Float(), nullable=False),
    sa.Column('lcos', sa.Float(), nullable=False),
    sa.Column('lcos_no_tes', sa.Float(), nullable=False),
    sa.Column('htf', sa.String(length=256), nullable=False),
    sa.Column('htf_attr', sa.PickleType(), nullable=True),
    sa.Column('material', sa.String(length=256), nullable=False),
    sa.Column('material_attr', sa.PickleType(), nullable=True),
    sa.Column('run_time', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_2_id'), 'result_2', ['id'], unique=False)
    op.create_table('costprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=False),
    sa.Column('with_tes', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['result_2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_costprofile_id'), 'costprofile', ['id'], unique=False)
    op.create_table('electricsplitprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=False),
    sa.Column('with_tes', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['result_2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electricsplitprofile_id'), 'electricsplitprofile', ['id'], unique=False)
    op.create_table('flowprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['caseparams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flowprofile_id'), 'flowprofile', ['id'], unique=False)
    op.create_table('loadprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['caseparams_2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loadprofile_id'), 'loadprofile', ['id'], unique=False)
    op.create_table('loadsplitprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('value', sa.PickleType(), nullable=False),
    sa.Column('with_tes', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['result_2.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loadsplitprofile_id'), 'loadsplitprofile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loadsplitprofile_id'), table_name='loadsplitprofile')
    op.drop_table('loadsplitprofile')
    op.drop_index(op.f('ix_loadprofile_id'), table_name='loadprofile')
    op.drop_table('loadprofile')
    op.drop_index(op.f('ix_flowprofile_id'), table_name='flowprofile')
    op.drop_table('flowprofile')
    op.drop_index(op.f('ix_electricsplitprofile_id'), table_name='electricsplitprofile')
    op.drop_table('electricsplitprofile')
    op.drop_index(op.f('ix_costprofile_id'), table_name='costprofile')
    op.drop_table('costprofile')
    op.drop_index(op.f('ix_result_2_id'), table_name='result_2')
    op.drop_table('result_2')
    op.drop_index(op.f('ix_result_id'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_caseparams_2_id'), table_name='caseparams_2')
    op.drop_table('caseparams_2')
    op.drop_index(op.f('ix_caseparams_id'), table_name='caseparams')
    op.drop_table('caseparams')
    op.drop_index(op.f('ix_case_id'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
